#!/bin/bash
sudo ifconfig eth0 172.26.14.10 netmask 255.255.255.0 up
sudo route add default gw 192.160.20.1
sudo ip addr show

sudo /etc/init.d/dbus start
sudo /etc/init.d/xrdp start

sudo umount /mnt/c && sudo mount -t drvfs C: /mnt/c -o metadata,uid=1000,gid=1000,umask=000
#,fmask=111

